### ISSUE TITLE
bug: "Hide community posts in home feed" no longer working

### ISSUE THREAD

**Issue by lnp5131** [YT-Advanced/ReX-patches#53] opened 2024-02-07 05:03 UTC
### Bug description

Community posts show in home feed when the option is toggled on. Already tried retoggling. 

### Additional context

Android 14
Pixel 8
YouTube v19.04.37

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by YT-Advanced** [comment] 2024-02-07 06:45
Repatch your app with Debugging patch, then try to reproduce this bug

**Comment by Issam28** [comment] 2024-02-10 09:46
Same here, it's not longer working.

**Comment by Issam28** [comment] 2024-02-11 07:29
Community posts are still present in subscription page

**Comment by YT-Advanced** [comment] 2024-02-11 07:48
> Community posts are still present in subscription page

latest patches ? Also share your settings

**Comment by Issam28** [comment] 2024-02-11 07:52
Yes latest patches. The problem seems to be fixed on the home page, but it's still there on the subscription page. Here are some screenshots.

![Screenshot_20240211-085046](https://github.com/YT-Advanced/ReX-patches/assets/22579217/5343750e-dbfe-4a57-9df9-e263a3035572)
![Screenshot_20240211-085004](https://github.com/YT-Advanced/ReX-patches/assets/22579217/e41b87a2-d7df-4fe5-bd39-58516f2aad2b)

**Comment by YT-Advanced** [comment] 2024-02-11 07:58
restart the app and try again ?

**Comment by Issam28** [comment] 2024-02-11 08:01
Did that, cleared the cache and force stopped the app. They're still there.

**Comment by YT-Advanced** [comment] 2024-02-11 08:08
weird, can you also send the log of the subscriptions tab also

**Comment by Issam28** [comment] 2024-02-11 08:18
[log.txt](https://github.com/YT-Advanced/ReX-patches/files/14231741/log.txt)

**Comment by YT-Advanced** [comment] 2024-02-11 08:42
I still cannot reproduce this issues in my devices, weird

**Comment by sams452m** [comment] 2024-02-11 08:43
> Community posts are still present in subscription page

![IMG_20240211_141156](https://github.com/YT-Advanced/ReX-patches/assets/143210060/bbe19679-4a42-4d41-8c33-661d34074b9d)

But there is setting available for hiding community post in subscription feed.

**Comment by YT-Advanced** [comment] 2024-02-11 08:44
@Issam28 Add this custom filter and tell me the result: `image_post_root`

**Comment by Issam28** [comment] 2024-02-11 08:47
@YT-Advanced I added these two custom filters : `post_base_wrapper`,` image_post_root`, and it seems it worked. It filtered the community posts in all pages.

**Comment by YT-Advanced** [comment] 2024-02-11 08:49
thanks, seem like Google is testing new community post type

**Comment by sams452m** [comment] 2024-02-11 08:58
> @YT-Advanced I added these two custom filters : `post_base_wrapper`,` image_post_root`, and it seems it worked. It filtered the community posts in all pages.

`post_base_wrapper` this will hide community post from channel also

**Comment by YT-Advanced** [comment] 2024-02-11 09:02
I pushed the new changes to integrations, repatch and let me know the result

**Closed by YT-Advanced** 2024-02-11 09:02 UTC
Labels: A/B Testing, wating for author

**Comment by Issam28** [comment] 2024-02-11 09:10
I repatched and retested, everything seems to be working now. Thanks for the quick fix.
